#!/usr/bin/env bash
# a Bash script that will display information about subdomains

get_dns_info() {
    local domain="$1"
    local subdomain="$2"
    
    local script
    script=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    
    echo "$subdomain $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

main() {
    if [ "$#" == 1 ]; then
        for subdomain in "www" "lb-01" "web-01" "web-02"; do
            get_dns_info "$1" "$subdomain"
        done
    elif [ "$#" == 2 ]; then
        get_dns_info "$1" "$2"
    else
        echo "Usage: $0 <domain> [subdomain]"
        exit 1
    fi
}

main "$@"
