#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that your servers are configured with the right hostnames
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
sudo apt-get install haproxy -y

# edit config file
server_config=\
"
frontend  http-front
        bind *:80
        default_backend http-back
backend http-back
        balance roundrobin
        server 276312-web-01 54.160.84.89:80 check
        server 276312-web-02 54.157.152.197:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
