#!/usr/bin/env bash
# check what's stopping  Nginx installation from listening on port 80
# Nginx must be running&listening on port 80 of all server’s active IPv4 IPs
# ../sites-enabled/default was deleted and replaced with a copy of
# ../sites-available/default,
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
